# Generated by Django 4.1.4 on 2023-01-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_coaching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_coaching',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coaching_images'),
        ),
    ]
