# Generated by Django 4.1.4 on 2023-02-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coaches',
            old_name='image',
            new_name='background',
        ),
        migrations.RemoveField(
            model_name='coaches',
            name='info',
        ),
        migrations.AddField(
            model_name='coaches',
            name='imagepop',
            field=models.ImageField(blank=True, null=True, upload_to='coaches_images'),
        ),
        migrations.AlterField(
            model_name='coaches',
            name='name',
            field=models.ImageField(blank=True, null=True, upload_to='coaches_images'),
        ),
    ]
